apiVersion: fabricator.cestus.io/v1alpha1
kind: Config
components:
  - name: codegenerator
    generator: fabricator-generate-project-go
    spec:
      goModule: code.cestus.io/libs/codegenerator
      repoURL: https://github.com/CestusIO/codegenerator
      isLib: true
  - name: "fabricator generate"
    generator: fabricator-generate-go
    spec:
      packageName: codegenerator